apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
configMapGenerator:
- name: app-settings
  literals:
  - DATABASE_URL=localhost:5432
  - APP_PORT=7070

- name: app-config
  files:
  - config.json
#  - settings.properties

- name: app-environment
  envs:
  - app.env

#secretGenerator:
#- name: app-secrets
#  literals:
#  - api-key=my-secret-key
#  - password=very-secret
